### ISSUE TITLE
Where does this work?

### ISSUE THREAD

**Issue by BoredLama** [maaAnandsheela/stremio-liv-addon#1]
I've seen this add-on in Stremio's catalog, but I can't seem to get it working anywhere.

In Stremio Web I get a CORS error (which is fine, i guess, not all add-ons work with the web version), but in Stremio Desktop it just buffers forever and on Stremio Android i just get an error when I try to stream.

So I'm confused where this should work, or maybe the streams are cached for longer then some stream expiration time leading to none of them working?

**Comment by maaAnandsheela** [comment]
Hi BoredLama

Sorry for late reply. Its my mistake should have mentioned in description it only works for users with Indian ip. Its region specific.

**Comment by maaAnandsheela** [comment]
If it doesn't work for you with indian ip then please mention the issue then so that I can fix it. BTW it works on browsers too no issue cors.

**Comment by BoredLama** [comment]
I just tried it with an indian IP but it seems the app is no longer online:
https://premiumfy.herokuapp.com/liv/manifest.json

It might also be a good ideea to write that it only works with an Indian IP in the add-on's description in the manifest, so other users do not also get confused.

**Comment by maaAnandsheela** [comment]
I migrated the app. New demo link has been updated and also stremio addons. Please check really sorry again. 
https://stremio.eu-gb.mybluemix.net/liv/manifest.json

**Comment by BoredLama** [comment]
I tested this with an indian IP, and it indeed works fine.

But all the streams have the same text now:
<img width="348" alt="Screen Shot 2019-07-01 at 14 35 24" src="https://user-images.githubusercontent.com/43473329/60433529-ba8fb980-9c0d-11e9-9c29-81e5d1e1fe16.png">

I think previously they used to show the quality of the stream.

**Comment by maaAnandsheela** [comment]
Actually this is the issue with some of the streams. I actually parse m3u8 manifest before displaying the streams thats why this issue persists in some streams because they have changed their manifest. I ll try and update the code to support these streams.
