### ISSUE TITLE
The add-on is down

### ISSUE THREAD

**Issue by danamag** [maaAnandsheela/stremio-liv-addon#2]
Gives a 404 error now

**Comment by danamag** [comment]
if this would work in a serverless scenario, you could use now.sh to host it, it's free

**Comment by maaAnandsheela** [comment]
Hi this addon is fine. Its working fine. Please check again and confirm.

**Comment by danamag** [comment]
Ah, works fine now on the desktop app, it does not work in the web app (probably due to browser limitations? it says "failed to fetch" on the Discover page on http://app.strem.io/shell-v4.4/ ), and i did not check the phone app.

But yeah, the add-on works so i'll close the issue.

**Comment by danamag** [comment]
thanks!
