### ISSUE TITLE
The add-on disappeared from the catalog

### ISSUE THREAD

**Issue by danamag** [maaAnandsheela/stremio-liv-addon#3]
It doesn't show in Stremio anymore. Here is the related reddit post:
https://www.reddit.com/r/StremioAddons/comments/d9vx8c/sonyliv_addon_removed/

**Comment by maaAnandsheela** [comment]
I have posted it again on stremio catalog. It will be up soon on catalog was error on hosting side thats why it disappeared.

**Comment by danamag** [comment]
looks like it's working now, at least for me

thanks!
